name: 'Install local pnl package'
description: 'Install PsyNeulink dependencies and editable PNL package'
inputs:
  features:  # id of input
    description: 'PsyNeuLink features to install'
    required: true
    default: ''

runs:
  using: "composite"
  steps:
    - name: OS dependencies
      shell: bash
      env:
        RUNNER_OS: ${{ runner.os }}
        HOMEBREW_NO_AUTO_UPDATE: 1
      # Composited actions can't use step conditionals.
      run: |
        case "$RUNNER_OS" in
          macOS*) brew install graphviz ;;
          Linux*) sudo apt-get install -y graphviz ;;
          Windows*) choco install --no-progress -y graphviz --version=2.38.0.20190211 ;;
          *) echo "Unsupported OS"; exit 1 ;;
        esac

    - name: Setup Python venv
      shell: bash
      run: |
        case "$RUNNER_OS" in
          macOS* | Linux*)
            export VIRTUAL_ENV='${{ runner.temp }}/_venv'; export PYTHON_LOC=$VIRTUAL_ENV/bin/ ;;
          Windows*)
            export VIRTUAL_ENV='${{ runner.temp }}\_venv'; export PYTHON_LOC=$VIRTUAL_ENV\\Scripts ;;
          *) echo "Unsupported OS"; exit 1 ;;
        esac
        python -m venv $VIRTUAL_ENV
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
        echo "$PYTHON_LOC" >> $GITHUB_PATH

    - name: Drop pytorch on x86
      shell: bash
      run: |
        if [ $(python -c 'import struct; print(struct.calcsize("P") * 8)') == 32 ]; then
          sed -i /torch/d requirements.txt
          # pywinpty is a transitive dependency and v1.0+ removed support for x86 wheels
          # terminado >= 0.10.0 pulls in pywinpty >= 1.1.0
          [[ ${{ runner.os }} = Windows* ]] && pip install "pywinpty<1" "terminado<0.10"
        fi

    - name: Python dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip wheel
        pip install -e .[${{ inputs.features }}]

    - name: "Cleanup old wheels"
      shell: bash
      run: |
        pip cache info
        INSTALLED=`pip list | sed 's/-/_/g' | sed 's/  */-/' | tail -n+3`
        CACHED=`pip cache list | cut -f 2,3 -d- | tail -n+3`
        for P in $CACHED; do
          # Remove cached and not installed
          if [ `echo $INSTALLED | grep -o $P | wc -l` == "0" ] ; then
            pip cache remove -v $P || true
          fi
        done
