name: PsyNeuLink Master AutoPR

on:
  schedule:
    - cron: '0 12 * * 0'
  workflow_dispatch:

jobs:
  master-autopr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.PNLHELP_SSH_PRIVATE_KEY }}
          ref: master
      - name: Create master update branch
        run: |
          git fetch origin devel:devel
          git reset --hard devel
      - name: Create master update PR
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
          branch: devel
          title: '[auto] devel'
          labels:
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
