name: PsyNeuLink Master AutoPR

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  master-autopr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.PNLHELP_SSH_PRIVATE_KEY }}
          ref: devel
      - name: Create master update PR
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
          branch: devel
          title: '[auto] devel'
          labels:
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
