name: PsyNeuLink Master AutoPR

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  master-autopr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.PNLHELP_SSH_PRIVATE_KEY }}
          ref: weekly-release
      - name: Create Master Update PR
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
          branch: weekly-release
          run: |
            git fetch origin devel:devel
            git reset --hard devel
          title: '[auto] devel'
          labels:
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
