name: PsyNeuLink Master AutoPR

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  master-autopr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PNLHELP_SSH_PRIVATE_KEY }}
          base: master
          branch: devel
          delete-branch: false
          title: '[auto] devel'
          labels:
            automated pr
          team-reviewers: |
            owners
            maintainers
          draft: false
