name: PsyNeuLink Master AutoPR

on:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  master-autopr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.PNLHELP_SSH_PRIVATE_KEY }}
          source_branch: devel
          destination_branch: master
          pr_title: '[auto] ${{ github.ref }}'
          pr_reviewer: "maintainers"
          draft: false
